name: Test xxh on pull request

on: pull_request

jobs:
  test-full:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install xde
      run: cd xde && pip install -r requirements.txt
    - name: xde build
      run: cd xde && ./xde build
    - name: xde up
      run: cd xde && ./xde up
    - name: xde test
      run: cd xde && ./xde test --not-interactive



