name: Test xxh on push

on: push

jobs:
  test-short:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install xxh
      run: pip install .
    - name: Run xxh
      run: xxh --version